[BUGFIX] - Fix crash-looping archiver and log panic (#1851)
The archive nodes were becoming unhealthy after reporting a panic in the
logs:

```
panic: interface conversion: interface {} is nil, not string
```

This error turned out to arise from a method to convert blockchain
errors into readable strings. After fixing it, we get

```
Error: archiver.start: (56:CANNOT_CALL_CONTRACT) Contract Returned Error | StreamRegistry.GetPaginatedStreamsGetPaginatedStreams smart contract call failed base_error: request timed out
```

This issue was arising when the start go routine encountered an error
while reading paginated streams from the registry. if this call fails,
the archiver will shut down. To fix, I reduced the default page size to
1k and added retries on the GetPaginatedStream call.